config/routes.rb
OmniauthShibbolethTestapp::Application.routes.draw do
  get "root/index"

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout

  match '/session_viewer' => 'session_viewer#index'
  
  root :to => 'root#index'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :shib_auth_url

  private
  def redirect_back_or_default
    redirect_to(request.referer || course_path)
  end

  def root_url
    "#{request.env['SCRIPT_NAME']}/"
  end

  def shib_auth_url
    "#{request.env['SCRIPT_NAME']}/auth/shibboleth"
  end

  def authenticate!
    if session[:user].nil?
      session[:return_url] = request.url
      redirect_to shib_auth_url and return
    end
    session[:return_url] = nil
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/session_viewer_controller.rb
class SessionViewerController < ApplicationController
  before_filter :authenticate!

  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:user] = {
      :uid => request.env["omniauth.auth"]["uid"],
      :name => request.env["omniauth.auth"]["info"]["name"],
      :email => request.env["omniauth.auth"]["info"]["email"],
      :affiliation => request.env["omniauth.auth"]["extra"]["raw_info"]["unscoped-affiliation"],
      :entitlement => request.env["omniauth.auth"]["extra"]["raw_info"]["entitlement"]
    }
    redirect_to session[:return_url], :flash => {:notice => "Welcome #{session[:user][:uid]}"}
  end

  def destroy
    session[:user] = nil
    redirect_to root_url, :flash => {:notice => "You have been successfuly signed out"}
  end

  def failure
    redirect_to root_url, :flash => {:error => "Could not log you in. #{params[:message]}"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/session_viewer_helper.rb
module SessionViewerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmniauthShibbolethTestapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/root/index.html.erb
<div id="page">
  <div id="sidebar">
    <ul id="sidebar-items">
      <li>
      <h3>Browse the documentation</h3>
      <ul class="links">
        <li><a href="http://guides.rubyonrails.org/">Rails Guides</a></li>
        <li><a href="http://api.rubyonrails.org/">Rails API</a></li>
        <li><a href="http://www.ruby-doc.org/core/">Ruby core</a></li>
        <li><a href="http://www.ruby-doc.org/stdlib/">Ruby standard librar
          y</a></li>
      </ul>
      </li>
    </ul>
  </div>

  <div id="content">
    <div id="header">
      <h1>omniauth-shibboleth testing application</h1>
      <h2>let's test your omniauth-shibboleth configuration!</h2>
    </div>

    <div id="getting-started">
      <h1>getting started</h1>
      <h2>here&rsquo;s how to get rolling:</h2>

      <ol>
        <li>
        <h2>customize to receive shibboleth attributes you need</h2>
        <p>edit $rails_root/config/initializers/omniauth.rb</p>
        </li>

        <li>
        <h2>confirm the attributes are passed by shibboleth sp</h2>
        <p>set :debug => true to confirm the environment variables passed by the frontend (e.g. apache). after editing omniauth.rb, you can check it by accessing <%= link_to 'session_viewer', session_viewer_url %>.</p>
        </li>

        <li>
        <h2>confirm the Auth Hash at session_viewer</h2>
        <p>At last, you can check Auth Hash generated by OmniAuth by setting :debug => false (or just remove it). To apply the setting, you need to restart Rails server. To restart Rails server, for example, in Passenger case, you just need to execute the following command:</p>
        <p>
        % touch $RAILS_ROOT/tmp/restart.txt
        </p>
        <p>After restarting the server, you can check the Auth Hash at <%= link_to 'session_viewer', session_viewer_url %>.</p>
        </li>
      </ol>
    </div>
  </div>

  <div id="footer">&nbsp;</div>
</div>

app/views/session_viewer/index.html.erb
<h1>Session Parameter Viewer</h1>

<p>
<pre>
<%= h session[:user] %>
</pre>
</p>

<p>
<%= link_to 'Signout', signout_url %>
</p>